-- Folsom Cafe & Resturent — one-time database setup.
-- Paste this whole file into Supabase Dashboard → SQL Editor → New query → Run.
-- Safe to run again later: it only creates what's missing.

CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('staff','kitchen','owner')),
  display_name  TEXT NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower ON users (LOWER(username));

CREATE TABLE IF NOT EXISTS menu_items (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  category     TEXT NOT NULL DEFAULT 'Others',
  price        INTEGER NOT NULL CHECK (price >= 0),
  image        TEXT DEFAULT '',
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
  legacy_id    TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---- v4 additions (item detail: description + estimated cook time) -----
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS cook_minutes INTEGER; -- NULL = unknown

CREATE TABLE IF NOT EXISTS orders (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_code    TEXT NOT NULL UNIQUE,
  customer_name  TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  table_no       TEXT NOT NULL,
  note           TEXT DEFAULT '',
  status         TEXT NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','accepted','preparing','cooked','served','cancelled')),
  total          INTEGER NOT NULL,
  source         TEXT NOT NULL DEFAULT 'customer' CHECK (source IN ('customer','staff')),
  created_by     BIGINT REFERENCES users(id),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id BIGINT REFERENCES menu_items(id),
  name         TEXT NOT NULL,
  price        INTEGER NOT NULL,
  qty          INTEGER NOT NULL CHECK (qty > 0)
);

CREATE TABLE IF NOT EXISTS order_status_history (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status   TEXT NOT NULL,
  changed_by  BIGINT REFERENCES users(id),
  changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per settlement: a single payment covers every unpaid order on a
-- table (the "table tab"). orders.payment_id NULL = still unpaid.
CREATE TABLE IF NOT EXISTS payments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_no   TEXT NOT NULL,
  method     TEXT NOT NULL CHECK (method IN ('cash','esewa','khalti','fonepay','card')),
  total      INTEGER NOT NULL CHECK (total >= 0),
  taken_by   BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_id BIGINT REFERENCES payments(id);

-- ---- v3 additions (takeaway, discounts, credit, waiter calls) ----------

-- Takeaway/counter orders have no table; queue_no is the daily pickup token.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_type TEXT NOT NULL DEFAULT 'dine'
  CHECK (order_type IN ('dine','takeaway'));
ALTER TABLE orders ADD COLUMN IF NOT EXISTS queue_no INTEGER;

-- Bill adjustments recorded on the payment: total = subtotal - discount + extra_charge.
ALTER TABLE payments ADD COLUMN IF NOT EXISTS subtotal INTEGER;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS discount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS extra_charge INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS note TEXT NOT NULL DEFAULT '';
-- allow 'credit' (udhaaro) as a settlement method
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_method_check;
ALTER TABLE payments ADD CONSTRAINT payments_method_check
  CHECK (method IN ('cash','esewa','khalti','fonepay','card','credit'));

-- Udhaaro ledger. amount > 0 = credit taken (bill settled on credit),
-- amount < 0 = repayment. Balance per customer = SUM(amount) grouped by phone.
CREATE TABLE IF NOT EXISTS credit_entries (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name  TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  amount         INTEGER NOT NULL,
  method         TEXT NOT NULL DEFAULT 'credit',
  payment_id     BIGINT REFERENCES payments(id),
  taken_by       BIGINT REFERENCES users(id),
  note           TEXT NOT NULL DEFAULT '',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Customer "call waiter" / "ask for bill" requests from the tracking page.
CREATE TABLE IF NOT EXISTS service_calls (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_no    TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('waiter','bill')),
  status      TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  resolved_by BIGINT REFERENCES users(id)
);

-- ---- v5 additions (in-café ordering lock) ------------------------------

-- Generic key→JSON settings store. First use: 'order_gate', the allowlist of
-- public IPs (the café's internet connection) permitted to place customer
-- orders, so people outside the café can't order from a public URL. One row
-- per setting; value is arbitrary JSON shaped by the feature that owns the key.
CREATE TABLE IF NOT EXISTS app_settings (
  key        TEXT PRIMARY KEY,
  value      JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_by BIGINT REFERENCES users(id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_status  ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_unpaid  ON orders(table_no) WHERE payment_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_items_order    ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_hist_order     ON order_status_history(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_created ON payments(created_at);
CREATE INDEX IF NOT EXISTS idx_credit_phone   ON credit_entries(customer_phone);
CREATE INDEX IF NOT EXISTS idx_calls_open     ON service_calls(table_no) WHERE status = 'open';

-- The Node server is the only client. In the default (dev) setup it connects
-- with the anon key, so the anon role gets full access. IMPORTANT: this means
-- the anon key works like a database password — keep .env private and never
-- ship this key in a browser app or a public git repo.
--
-- PRODUCTION: switch the server to the service_role key, then run
-- supabase-hardening.sql ONCE to DROP these anon policies (see DEPLOYMENT.md).
-- RLS stays enabled with no anon policy, so a leaked anon key can touch nothing
-- while the server (service_role) keeps full access.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','menu_items','orders','order_items','order_status_history','payments','credit_entries','service_calls','app_settings'] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE tablename = t AND policyname = 'server_full_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY server_full_access ON %I FOR ALL TO anon USING (true) WITH CHECK (true)', t
      );
    END IF;
  END LOOP;
END $$;
